### ISSUE TITLE
Cannot read properties of undefined (reading 'type') after upgrading to 0.14.0 from 0.12.0

### ISSUE THREAD

**Issue by AndyGleed** [playwright-community/eslint-plugin-playwright#139]
Hi, I have just upgraded to v0.14.0 and now see an error when running `eslint **/*.ts`

```
> eslint **/*.ts


Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting D:\Automation\bc-automation\src\components\graphite\listing.ts:59
    at isLiteral (D:\Automation\bc-automation\node_modules\eslint-plugin-playwright\lib\utils\ast.js:26:18)
    at isStringLiteral (D:\Automation\bc-automation\node_modules\eslint-plugin-playwright\lib\utils\ast.js:32:12)
    at CallExpression (D:\Automation\bc-automation\node_modules\eslint-plugin-playwright\lib\rules\no-networkidle.js:26:51)
    at D:\Automation\bc-automation\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\Automation\bc-automation\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\Automation\bc-automation\node_modules\eslint\lib\linter\node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (D:\Automation\bc-automation\node_modules\eslint\lib\linter\node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (D:\Automation\bc-automation\node_modules\eslint\lib\linter\node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (D:\Automation\bc-automation\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
```

If I look at my code file listing.ts at line 59, it is has:
`await this.page.waitForLoadState();`

If I comment that out and run it again, it moves on to the next line that has the same waitForLoadState().

If I revert, everything is of course OK again.

VSCode v 1.79.2
Windows 11
Node.js v16.17.1

Any thoughts appreciated :)

**Comment by mskelton** [comment]
Sorry about that, this is fixed now!
