### ISSUE TITLE
expect-expect on 0.18.0 fails on standalone functions

### ISSUE THREAD

**Issue by iyefrat** [playwright-community/eslint-plugin-playwright#179]
Steps to reproduce:

run eslint with `eslint-plugin-playwright` 0.18.0 (I'm using `eslint 8.36.0` if that matters) on the following file:
```
import { Page, expect } from '@playwright/test';

export async function assertionFunction({ page }: { page: Page }) {
  await expect(page).toHaveURL('https://example.com');
}
```

You'll get the following error:
```
Oops! Something went wrong! :(

ESLint: 8.36.0

TypeError: Cannot read properties of undefined (reading 'getAncestors')
Occurred while linting /repoPath/temp.ts:4
Rule: "playwright/expect-expect"
    at CallExpression (/repoPath/node_modules/.pnpm/eslint-plugin-playwright@0.18.0_eslint@8.36.0/node_modules/eslint-plugin-playwright/lib/rules/expect-expect.js:28:57)
    at ruleErrorHandler (/repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/linter.js:1118:28)
    at /repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /repoPath/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/linter/linter.js:1153:32
```

This works on 0.17.0 so I assume it was introduce by https://github.com/playwright-community/eslint-plugin-playwright/pull/172

**Comment by iyefrat** [comment]
Thanks for the quick turnaround!
