### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kaiyoma** [playwright-community/eslint-plugin-playwright#192]
I am running into problems after upgrading from 0.20.0 to 0.21.0:

```
00:09:12  Oops! Something went wrong! :(
00:09:12  
00:09:12  ESLint: 8.56.0
00:09:12  
00:09:12  RangeError: Maximum call stack size exceeded
00:09:12  Occurred while linting /home/jenkins/workspace/Geiger/geiger-upgrade-deps/tools/test-e2e/playwright/e2e/provisioning/studios/workspaceRebasing.pw.ts:725
00:09:12  Rule: "playwright/missing-playwright-await"
00:09:12      at SourceCode.getScope (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/source-code/source-code.js:770:13)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:344:34)
00:09:12    ...20 lines omitted...
00:09:12      at SourceCode.getScope (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/source-code/source-code.js:770:13)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:344:34)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
00:09:12      at checkValidity (/home/jenkins/workspace/Geiger/geiger-upgrade-deps/common/temp/node_modules/.pnpm/eslint-plugin-playwright@0.21.0_eslint@8.56.0/node_modules/eslint-plugin-playwright/dist/index.js:349:15)
```

**Comment by kaiyoma** [comment]
This might be partially our fault, since we have some code that follows an odd paradigm:

```
      // eslint-disable-next-line playwright/missing-playwright-await
      const rebuildAlertsAssertion = expect(
        page.getByRole('alert').filter({
          has: page.getByText(rebuildAlertMessage),
        }),
      ).toBeHidden();
      await page.getByTestId('workspace.rebase.button').click();
      await rebuildAlertsAssertion;
```

I'll look into making our code less weird, but I still expect eslint to not crash.

**Comment by kaiyoma** [comment]
> @kaiyoma I tested the code you shared and it worked fine for me. Can you share the full file that is failing?

It's proprietary so I can't. 😞 Is there some other kind of debugging I can do to help?

**Comment by mskelton** [comment]
@kaiyoma What I would recommend is deleting tests one by one from the file till you identify the test that cause it to fail. Once you have that, then if you could send it over that would be fantastic.

**Comment by mskelton** [comment]
@kaiyoma Are you still encountering this issue?

**Comment by mskelton** [comment]
Closing due to lack of response.
